name: 'upload file on release'
description: 'Upload a release asset to an existing release in your repository'
author: 'Fhwang0926'
inputs:
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
  asset_name:
    description: 'The name of the asset you want to upload'
    required: true
  asset_label:
    description: 'The label of the asset you want to upload'
    required: false
outputs:
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
